name: Build release assets

on:
    release:
        types: [published]

jobs:
    draft:
        environment: production
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Write .env to build
              env:
                  DOTENV: '${{ secrets.DOTENV }}'
              run: echo "$DOTENV" >> ./client/.env
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - name: Install dependencies and build
              run: npm run package
            - name: Upload release assets
              id: upload-release-asset
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ github.ref }}
                  file: ./build.tar.gz
                  asset_name: $tag-build.tar.gz
                  asset_content_type: application/gzip
                  overwrite: true
